"""Explicaciones cortas por campo — admin Jazzmin y columna «Cómo llenar» del Excel."""

from __future__ import annotations

# Texto breve: qué cargar / validar en cada campo del caso.
FIELD_HINTS: dict[str, str] = {
    "hab_id": "ID del edificio en Habitable — precarga; no inventar otro.",
    "certificado": "Código de certificado de Fase I — solo consultar/validar.",
    "nombre_hab": "Nombre según Habitable. Si está mal, corríjalo en §3.",
    "etiqueta_f1": "Etiqueta de Fase I (en este universo: ROJO). Validar en §3.",
    "fecha_f1": "Fecha de la inspección rápida (Fase I) — solo referencia.",
    "inspector_f1": "Quién inspeccionó en la 1.ª ronda — solo referencia.",
    "direccion_hab": "Dirección precargada. Si no coincide con el sitio, corrija en §3.",
    "muni_parr": "Municipio / parroquia precargados.",
    "pisos_f1": "Pisos/sótanos reportados en Fase I. Confirme en §3 o §4.",
    "riesgos_f1": "Riesgos externos/severos anotados en Fase I — contraste con lo visto.",
    "colapso_f1": "Indicador de colapso reportado en Fase I.",
    "piso_crit_f1": "Piso crítico de Fase I — confirme o actualice en §5.",
    "acciones_f1": "Acciones sugeridas en Fase I (acordonar, apuntalar…).",
    "obs_f1": "Observaciones del inspector Fase I — léalas antes de decidir.",
    "gps_hab": "GPS referencial Habitable. El GPS de visita 2 va en §4.",
    "lat": "Latitud decimal (mapa). Suele venir de la precarga.",
    "lng": "Longitud decimal (mapa). Suele venir de la precarga.",
    "score": "0–100 (fijo). Bandas: 80+ Muy alta · 60–79 Alta · 40–59 Media · 20–39 Baja-media · 0–19 Baja. Corregir solo en §3.",
    "banda": "Tramo del score (fijo). No es la prioridad operativa de §10. Corregir solo en §3.",
    "puestos": "Orden relativo en la cola (fijo) — referencia operativa.",
    "score_detalle": "Qué ítems sumaron al score (fijo). Explique el resultado con esta lista.",
    "prob_rel": "Texto de probabilidad relativa ligado a la banda (fijo).",

    "val_edificio": "¿El ID/nombre corresponde al inmueble visitado?",
    "corr_nombre": "Solo si §3 edificio = No/Parcial: nombre correcto del sitio.",
    "corr_direccion": "Solo si corrige: dirección real (actualiza precarga al guardar).",
    "corr_muni_parr": "Solo si corrige: municipio/parroquia correctos.",
    "val_etiqueta": "¿Confirma la etiqueta Habitable (rojo / amarillo u otra)? Documente si duda.",
    "corr_etiqueta": "Solo si la etiqueta Fase I estaba mal (ej. no es ROJO).",
    "val_geometria": "¿Coinciden pisos/sótanos/uso con lo visto en campo?",
    "corr_pisos": "Solo si corrige geometría: ej. «11 / 1».",
    "corr_gps": "Solo si el GPS Habitable está mal (lat, lng).",
    "val_ranking": "¿El score refleja la gravedad vista en visita 2?",
    "corr_score": "Solo si el ranking estaba mal: score correcto 0–100.",
    "corr_banda": "Solo si corrige la banda de prioridad.",
    "correcciones": "Nota libre opcional (matices). Si ya llenó «… correcto», puede quedar vacío.",
    "coordinador_asignado": "Quién coordina el caso (admin asigna al coordinador).",
    "inspector_asignado": "Ingeniero/inspector responsable de la visita 2.",
    "revisor_asignado": "No se asigna manualmente. Quien revise desde la bandeja queda registrado en el historial.",
    "nombre_conf": "Nombre del edificio confirmado en sitio (visita 2).",
    "fecha_v2": "Fecha de esta visita detallada.",
    "gps_v2": "GPS tomado en la visita 2 (lat, lng), si lo midió.",
    "evaluadores_v2": "Nombres de quienes evaluaron en campo.",
    "supervisor_v2": "Supervisor del equipo / cuadrilla.",
    "uso": "Uso actual: vivienda, mixto, comercio, etc.",
    "pisos_conf": "N.º de pisos confirmados en visita 2.",
    "sotanos_conf": "N.º de sótanos / semisótanos confirmados.",
    "sistema": "Sistema estructural observado (pórticos, muros, mixto…).",
    "ocupacion": "Estado de ocupación (desalojado, parcial, irregular…).",
    "peligro_aledanos": "¿Hay riesgo para vecinos o vía pública?",
    "piso_crit_v2": "Piso o zona más crítica ahora (ej. PB, piso 5).",
    "pct_columnas": "% de columnas con daño relevante (escala del listado).",
    "inclinacion": "¿Hay inclinación? Obligatorio al elevar (no Pendiente). Si midió Δ, complete el campo Δ.",
    "delta_incl": "OBLIGATORIO si inclinación = «Sí — con medición Δ»: valor y unidad.",
    "dano_vigas": "Severidad A (leve) / B / C (grave) en vigas (síntesis §5).",
    "dano_losas": "Severidad A/B/C en losas (síntesis). Si afecta varios niveles, detalle en §6 Losas.",
    "riesgo_fachada": "Severidad A/B/C de riesgo de caída de fachada.",
    "analisis_libre": "Síntesis del ingeniero: qué vio y por qué importa.",
    "col_mec": "OBLIGATORIO si severidad columnas A/B/C: mecanismo (corte, flexión…).",
    "col_nivel": "Severidad A/B/C de columnas.",
    "col_evidencia": "OBLIGATORIO si severidad columnas A/B/C: ubicación (pisos/ejes) y evidencia.",
    "vig_mec": "OBLIGATORIO si severidad vigas A/B/C: mecanismo de daño.",
    "vig_nivel": "Severidad A/B/C de vigas.",
    "vig_evidencia": "OBLIGATORIO si severidad vigas A/B/C: ubicación y evidencia.",
    "mur_mec": "OBLIGATORIO si severidad muros A/B/C: mecanismo.",
    "mur_nivel": "Severidad A/B/C de muros.",
    "mur_evidencia": "OBLIGATORIO si severidad muros A/B/C: ubicación y evidencia.",
    "los_mec": "OBLIGATORIO si severidad losas A/B/C: mecanismo.",
    "los_nivel": "Severidad A/B/C de losas.",
    "los_evidencia": "OBLIGATORIO si severidad losas A/B/C: pisos/niveles y evidencia.",
    "escaleras": "Estado de escaleras y vías de evacuación.",
    "preexistentes": "Daños anteriores al sismo (no atribuirlos al 24-jun-2026).",
    "mam_mec": "Mecanismo en mampostería no portante.",
    "mam_nivel": "Severidad A/B/C de mampostería.",
    "mam_diag": "OBLIGATORIO si severidad mampostería A/B/C: diagnóstico (fisuras, desprendimiento…).",
    "procedimientos_catalogo": "Como Excel Metrados: Sí + ubicación, cantidad, unidad, severidad, acción, confianza y nota en la misma fila.",
    "proc_codigos": "Se llena con los Sí de la tabla; puede añadir códigos extra separados por coma.",
    "repar_viable": "¿Es viable reparar con la información actual?",
    "proc_notas": "Secuencia, shoring, acotamiento y supuestos del ingeniero.",
    "area_aprox_m2": "Área aproximada del edificio o del alcance a intervenir (m²).",
    "n_viviendas": "N.º estimado de viviendas / unidades.",
    "vol_escombros_m3": "Volumen estimado de escombros (m³), si aplica.",
    "m_fachada_riesgo": "m lineales o m² de fachada en riesgo (aclare en notas).",
    "niveles_intervenir": "Ej. PB+1, pisos 4–6, todos.",
    "pct_estructura_intervenir": "Porción de estructura a intervenir (misma escala que % columnas).",
    "metrado_confianza": "Alta (midió/contó) · Media · Estimada.",
    "metrado_notas": "Supuestos del metrado. El detalle tipificado va en las líneas de metrado.",
    "estado_2da": (
        "En Excel: solo la etapa actual y el siguiente paso de su rol. "
        "Al cargar se valida la transición (igual que el panel web)."
    ),
    "decision_D": "D2 reparar por regla; D1 si faltan estudios; D3/D4 solo última instancia.",
    "complementos_D": "Solo D1: códigos GEO,ENS,MOD,MON,INV,REI,ALE,OTR separados por coma.",
    "complemento_plazo": "Solo D1: fecha objetivo de los complementos.",
    "complemento_detalle": "Solo D1: qué falta, entregable y responsable.",
    "magnitud_M": "Obligatorio si D2 (M1…M4). Si no es D2: N/A.",
    "prioridad": "Inmediata / Alta / Programable según riesgo operativo.",
    "medidas": "Medidas inmediatas: acordonar, desalojar, apuntalar…",
    "justificacion": "Por qué esa decisión D (texto para el revisor).",
    "n_fotos": "Cuántas fotos de evidencia adjuntará (mín. 3 para PDF/cierre).",
    "firmas": "Quién elaboró / revisó / aprobó (texto).",
    "resumen_ejecutivo": "1–2 párrafos claros para coordinación (lenguaje de negocio).",
    # Líneas de metrado (inline)
    "orden": "Orden de aparición en el informe / Excel.",
    "codigo_partida": "Código del catálogo de partidas (desplegable).",
    "elemento": "Elemento estructural o de mampostería medido.",
    "id_pln01": "ID del elemento en el plano PLN-01 (p. ej. PB-C6). Ata el arreglo al croquis.",
    "piso_pln": "Piso del plano (PB, P1…). Se infiere del ID si se deja vacío.",
    "tipo_apuntamiento": "Post-sísmico: preventivo (estabilizar) vs de trabajo (durante la intervención).",
    "ubicacion": "Texto libre de apoyo (torre/zona). Preferir id_pln01 para el vínculo al plano.",
    "cantidad": "Cantidad medida o estimada.",
    "unidad": "Unidad (m, m², und, glb…).",
    "severidad": "Severidad asociada A/B/C si aplica.",
    "accion": "Acción prevista (reparar, reforzar, demoler…).",
    "confianza": "Confianza de esta línea de metrado.",
    "nota": "Si acción = Otro, la nota es OBLIGATORIA al elevar.",
}


def hint_for(field_name: str, fallback: str = "") -> str:
    return FIELD_HINTS.get(field_name, fallback) or fallback
