"""Personalización Jazzmin — CPEH Fase II ROJO (identidad portal CPEH)."""
JAZZMIN_SETTINGS = {
    "site_title": "CPEH · Habitabilidad",
    "site_header": "Seguimiento inspecciones ROJO",
    "site_brand": "Fase II · ROJO",
    "site_logo": "img/logo-cpeh-sidebar.svg",
    "site_logo_classes": "brand-image-cpeh elevation-2",
    "site_icon": "img/logo-cpeh-sidebar.svg",
    "login_logo": None,
    "login_logo_dark": None,
    "welcome_sign": "Comisión Presidencial para la Evaluación de Habitabilidad de Infraestructuras",
    "copyright": "Comisión Presidencial para la Evaluación de Habitabilidad de Infraestructuras",
    "search_model": ["inspecciones.CasoRojo"],
    # Barra superior: solo atajos diarios (el resto vive en el menú izquierdo)
    "topmenu_links": [
        {"name": "Inicio", "url": "admin:index", "permissions": ["inspecciones.view_casorojo"]},
        {
            "name": "Dashboard",
            "url": "/operacion/",
            "new_window": True,
            "permissions": ["inspecciones.view_casorojo"],
        },
        {
            "name": "Mapa",
            "url": "/mapa/",
            "new_window": True,
            "permissions": ["inspecciones.view_casorojo"],
        },
        {
            "name": "Asignación",
            "url": "/asignacion/",
            "new_window": True,
            # Coordinadores tienen auth.view_user (ver asegurar_permisos_grupos)
            "permissions": ["auth.view_user"],
        },
        {"name": "Mi perfil", "url": "/perfil/", "permissions": ["inspecciones.view_casorojo"]},
    ],
    # Menú lateral: herramientas agrupadas (no saturan la navbar)
    "custom_links": {
        "Operación": [
            {
                "name": "Dashboard BI",
                "url": "/operacion/",
                "icon": "fas fa-chart-line",
                "permissions": ["inspecciones.view_casorojo"],
            },
            {
                "name": "Asignación de casos",
                "url": "/asignacion/",
                "icon": "fas fa-tasks",
                "permissions": ["auth.view_user"],
            },
            {
                "name": "Asignación por lote (Excel)",
                "url": "/asignacion/lote/",
                "icon": "fas fa-file-excel",
                "permissions": ["auth.add_user"],
            },
            {
                "name": "Mapa GPS",
                "url": "/mapa/",
                "icon": "fas fa-map-marked-alt",
                "permissions": ["inspecciones.view_casorojo"],
            },
            {
                "name": "Cargar Excel",
                "url": "/import/excel/",
                "icon": "fas fa-file-upload",
                "permissions": ["inspecciones.change_casorojo"],
            },
            {
                "name": "Listado de casos",
                "url": "/admin/inspecciones/casorojo/",
                "icon": "fas fa-list",
                "permissions": ["inspecciones.view_casorojo"],
            },
        ],
        "Equipo": [
            {
                "name": "Mi perfil",
                "url": "/perfil/",
                "icon": "fas fa-user-edit",
                "permissions": ["inspecciones.view_casorojo"],
            },
            {
                "name": "Nombres del equipo",
                "url": "/perfil/equipo/",
                "icon": "fas fa-id-card",
                "permissions": ["auth.view_user"],
            },
            {
                "name": "Gestión de usuarios",
                "url": "/gestion/usuarios/",
                "icon": "fas fa-user-shield",
                "permissions": ["auth.add_user"],
            },
        ],
        "Ayuda": [
            {
                "name": "Tutorial del sistema",
                "url": "/admin/#tutorial-sistema",
                "icon": "fas fa-graduation-cap",
                "permissions": ["inspecciones.view_casorojo"],
            },
            {
                "name": "Health API",
                "url": "/api/health/",
                "icon": "fas fa-heartbeat",
                "permissions": ["auth.view_user"],
            },
        ],
    },
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    # Satélites del caso (se editan dentro de la ficha, no como listados sueltos)
    "hide_models": [
        "inspecciones.CredencialEmitida",
        "inspecciones.EvidenciaFoto",
        "inspecciones.CroquisAdjunto",
        "inspecciones.InformePdfAdjunto",
        "inspecciones.HistorialEstado",
        "inspecciones.HistorialDetallado",
        "inspecciones.LineaMetrado",
    ],
    "order_with_respect_to": [
        "Operación",
        "inspecciones",
        "Equipo",
        "Ayuda",
        "auth",
        "inspecciones.CasoRojo",
        "inspecciones.EquipoBrigada",
        "inspecciones.PartidaCatalogo",
        "inspecciones.Procedimiento",
    ],
    "icons": {
        "Operación": "fas fa-briefcase",
        "Equipo": "fas fa-user-friends",
        "Ayuda": "fas fa-life-ring",
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
        "inspecciones": "fas fa-hard-hat",
        "inspecciones.CasoRojo": "fas fa-building",
        "inspecciones.EquipoBrigada": "fas fa-users",
        "inspecciones.Procedimiento": "fas fa-toolbox",
        "inspecciones.PartidaCatalogo": "fas fa-tags",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": "css/cpeh_admin.css",
    "custom_js": "js/cpeh_sidebar.js",
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "inspecciones.casorojo": "collapsible",
    },
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "flatly",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
